version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: tyson
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3305:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["debug"]
    volumes:
      - ./app:/usr/app
    ports:
      - '5001:5000'