version: "3.8"

x-mysql-airflow-env: &mysql_airflow_env
  MYSQL_DATABASE: ${MYSQL_AIRFLOW_DATABASE}
  MYSQL_USER: ${MYSQL_AIRFLOW_USER}
  MYSQL_PASSWORD: ${MYSQL_AIRFLOW_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_AIRFLOW_PASSWORD}
  MYSQL_HOST: ${MYSQL_AIRFLOW_HOST}

x-mysql-app-env: &mysql_app_env
  MYSQL_DATABASE: ${MYSQL_APP_DATABASE}
  MYSQL_USER: ${MYSQL_APP_USER}
  MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_APP_PASSWORD}
  MYSQL_HOST: ${MYSQL_APP_HOST}
  MYSQL_PORT: ${MYSQL_APP_PORT}

x-common-airflow: &airflow_common
    build:
      context: .
      dockerfile: Dockerfile.airflow
    volumes:
      - "./airflow/dags:/root/airflow/dags"
    environment:
      <<: *mysql_airflow_env
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "mysql+pymysql://${MYSQL_AIRFLOW_USER}:${MYSQL_AIRFLOW_PASSWORD}@${MYSQL_AIRFLOW_HOST}:${MYSQL_AIRFLOW_PORT}/${MYSQL_AIRFLOW_DATABASE}"
      AIRFLOW__CORE__PARALLELISM: 2
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DAG_DIR_LIST_INTERVAL: 15
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    depends_on:
      airflow-db:
        condition: service_healthy

services:
  airflow-db:
    image: mysql:8
    environment:
      << : *mysql_airflow_env
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  
  app-db:
    image: mysql:8
    environment:
      << : *mysql_app_env
    ports:
      - '3305:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    environment: *mysql_app_env
    depends_on:
      app-db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: ["debug"]
    environment:
      << : *mysql_app_env
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./app:/src/app
      - ./tests:/src/tests
    ports:
      - '5001:5000'
    depends_on:
      app-db:
        condition: service_healthy

  airflow-init:
      << : *airflow_common
      entrypoint: ["/bin/sh","-c"]
      command:
        - |
          airflow db migrate
          airflow users create \
          --username admin \
          --password admin \
          --firstname airflow \
          --lastname airflow \
          --role Admin \
          --email airflow@airflow.org
      restart: on-failure

  airflow-webserver:
    << : *airflow_common
    command: airflow webserver
    ports:
      - '8080:8080'
    container_name: airflow_webserver
    depends_on:
      - airflow-init
    restart: always

  airflow-scheduler:
    << : *airflow_common
    command: airflow scheduler
    container_name: airflow_scheduler
    depends_on:
      - airflow-init
    restart: always

