name: Docker Compose Test App Workflow

on:
  push:
    branches: [ master ]

env:
  MYSQL_APP_USER: tyson
  MYSQL_APP_PASSWORD: root
  MYSQL_APP_DATABASE: apifun
  MYSQL_APP_HOST: app-db
  MYSQL_APP_PORT: 3306
  SECRET_KEY: himynameistyson

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Test Application
      run: make test
